fix for :    Terraform Version: 0.7.5
cartest/terraform-microservice pull request #8
Opened 2016-10-12 14:31 UTC by madpawel

This is fix for TF 0.7.5 error:

    Terraform Version: 0.7.5
    Resource ID: aws_launch_configuration.launch_configuration
    Mismatch reason: attribute mismatch: security_groups.770011567

2016-10-12 14:35 UTC, edmundcraske requested changes

2016-10-12 14:35 UTC, edmundcraske commented on variables.tf
> +variable "user_data_scritp_path" {
s/scritp/script/

2016-10-12 14:35 UTC, edmundcraske commented on variables.tf
> +  description = "Path to user data script which will be executed drunig instance boot"
s/drunig/during/

2016-10-13 13:35 UTC, dmatusiewicz approved these changes
Looks good.

2016-10-13 13:35 UTC, merged