Story opsteam 228
cartest/terraform-microservice pull request #9
Opened 2016-10-18 16:28 UTC by dmatusiewicz

Adding support for ELB.

2017-01-17 11:52 UTC, Zordrak requested changes
Need some serious review before this is anywhere near pullable.

2017-01-17 11:52 UTC, Zordrak commented on iam.tf
> -resource "aws_iam_role_policy_attachment" "iam_role_policy_attachment" {
What's going on here / and why something left commented in any case?

2017-01-17 11:52 UTC, Zordrak commented on sg.tf
> +resource "aws_security_group_rule" "ssg_ingress" {
Why are we creating security group rules inside the module? Rules should be created at the level above where the module is being called from.

2017-01-17 11:52 UTC, Zordrak commented on variables.tf
> +  default     = ""
Why has empty default been added here? Should be a mandatory input.

2017-01-17 11:52 UTC, Zordrak commented on templates/consul_asg.sh
> +#!/bin/bash
Why is this here? Doesn't look like this has any place being in the generic terraform microservice module(!)

2017-01-17 13:11 UTC, madpawel commented on templates/consul_asg.sh
> +#!/bin/bash
Fixed, file removed we don't need it here

2017-01-18 11:14 UTC, Zordrak approved these changes

2017-01-18 11:14 UTC, merged